# Generated by Django 5.1.1 on 2025-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_electricitytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
