# Generated by Django 5.1.1 on 2025-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataplan_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplan',
            name='network_code',
            field=models.CharField(default='01', max_length=5),
        ),
    ]
