# Generated by Django 5.1.1 on 2025-06-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dataplan_network_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPlan',
        ),
    ]
