# Generated by Django 5.1.1 on 2025-06-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_dataplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CablePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('dstv', 'DSTV'), ('gotv', 'GOTV'), ('startimes', 'Startimes')], max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
