# Generated by Django 5.1.1 on 2025-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_smartcardhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablepackage',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitytransaction',
            name='response_log',
            field=models.TextField(blank=True),
        ),
    ]
